---
git:
  depth: 1
sudo: false
language: node_js
cache:
  directories:
  - node_modules
  - $HOME/.yarn-cache
  - packages/vostok-authentication/node_modules
  - packages/vostok-authorization/node_modules
  - packages/vostok-command-line/node_modules
  - packages/vostok-connector-postgres/node_modules
  - packages/vostok-framework/node_modules
  - packages/vostok-mocking/node_modules
  - packages/vostok-resolver/node_modules
  - packages/vostok-type/node_modules

node_js:
- '7.6.0'

before_install: .travis/before_install.sh
after_success: .travis/after_success.sh
script:
  - npm run lint
  - npm run bootstrap
  - npm run test
  - npm run codecov
