---
git:
  depth: 10
sudo: false
language: node_js
cache:
  directories:
  - node_modules
  - $HOME/.yarn-cache

node_js:
- '7'

script:
- 'if [ -n "${LINT-}" ]; then npm run lint ; fi'
- npm run bootstrap
- npm run build
- npm run test
- ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.info

matrix:
  fast_finish: true
  include:
    - node_js: "node"
      env: LINT=true
